### ISSUE TITLE
how to disable cfg-lock in bios？

### ISSUE THREAD

**Issue by JoePx** [xiecang/Hackintosh-B760M-12490F-6600xt#1]
how to disable cfg-lock in bios？

**Comment by xiecang** [comment]
Yes, it is necessary to disable cfg-lock.

**Comment by xiecang** [comment]
I'll cut a picture after work.

**Comment by xiecang** [comment]
I was under the impression that the path was "startup -> Bios Write Protection", but I'm not very sure.

**Comment by xiecang** [comment]
![image](https://github.com/xiecang/Hackintosh-B760M-12490F-6600xt/assets/16369161/6f90403e-d121-43cc-a1d4-ab68e5accccc)

**Comment by JoePx** [comment]
This doesn't seem to be CFG lock. I followed the methods online and tried modifying the CFG lock address in UEFI, but I received a UEFI write protection prompt. I guess it's not possible, and I'm not sure how much it would affect performance without this.

**Comment by xiecang** [comment]
[CFG-Lock is a setting in your BIOS that allows for a specific register(in this case the MSR 0xE2) to be written to. ](https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#what-is-cfg-lock)

On my motherboard, the "BIOS Flash Protection" setting is described as "Enable Flash Protection Range Registers", and disabling this option does work for me.

If that doesn't solve your problem, try enabling Kenel Quicks "AppleCpuPmCfgLock", "AppleXcpmCfgLock" in config.plist.
