### ISSUE TITLE
朋友你好，感谢分享efi，我的主板和你一样，但是在安装界面无法使用键盘和鼠标，请问有解决办法嘛

### ISSUE THREAD

**Issue by Y-B0** [xiecang/Hackintosh-B760M-12490F-6600xt#2]

**Comment by xiecang** [comment]
PickerAttributes 这个值设置为 17 试试
```
			<key>PickerAttributes</key>
			<integer>17</integer>
```

OpenCore Configurator 的路径是 Misc --> boot
<img width="1307" alt="image" src="https://github.com/xiecang/Hackintosh-B760M-12490F-6600xt/assets/16369161/7354cb87-e039-42ff-910f-19648c621511">

**Comment by Y-B0** [comment]
这个值倒是一样的，我发现是鼠标能动，但是键盘不能动，有时候在那个界面代一段时间后就卡死了，
或者点continue或者install...都会卡死。是显卡的问题嘛？我的显卡也是挑战者6600xt[image:
D63B6693C42AB009F90BD7C853F54111.png]

xiecang ***@***.***> 于2023年6月20日周二 21:28写道：

**Comment by xiecang** [comment]
键盘可以检查下 UEFI --> Input --> KeySupport 是否是勾选状态，应该勾选了才生效的
这个应该和显卡无关，是 opencore 的配置问题

<img width="1304" alt="image" src="https://github.com/xiecang/Hackintosh-B760M-12490F-6600xt/assets/16369161/1f2b8083-0d6a-474b-80a1-d97b27e63dd8">
