### ISSUE TITLE
大佬主板跟你一样CPU13600KF，需要什么改动吗

### ISSUE THREAD

**Issue by puwindtz** [xiecang/Hackintosh-B760M-12490F-6600xt#3]
CPU：13代intel i5 13600KF  
主板：铭瑄B760M终结者 D4  wifi  a211   BIOS更新到最新的了2023/7/15
内存：金百达银爵 16*2 3600 海力士颗粒
固态：海力士p440pro 
显卡：盈通6650xt游戏高手

**Comment by xiecang** [comment]
6650XT 需要仿冒显卡驱动，可以参照这里改下
https://imacos.top/2022/07/31/rx6950xt-rx6650xt/

**Comment by apu-li** [comment]
感谢 已经安装上了，
但是蓝牙我根据网上教程配置还是不行
网卡是 AX211
wifi正常蓝牙一直配不成功，打不开，想问下有啥建议吗
![image](https://github.com/xiecang/Hackintosh-B760M-12490F-6600xt/assets/104669530/ecb9c39e-bc96-441f-b4af-ace93e81890a)

**Comment by xiecang** [comment]
因为我用的是免驱的网卡，配置里没配这部分

我搜了下 macOS 12 之后的 Intel 无线网卡有一些变化

使用 BlueToolFixup.kext 替代掉 IntelBluetoothInjector.kext 即可。

BlueToolFixup.kext 可以从这里下载：https://github.com/acidanthera/BrcmPatchRAM/releases

最终使用驱动是这两个：

    BlueToolFixup.kext
    IntelBluetoothFirmware.kext

**Comment by puwindtz** [comment]
感谢，主要原因不是因为这个，后面我看过一些资料，发现是USB的问题（蓝牙占用到了），这个需要重新定制，重新定制后就可以了
