### ISSUE TITLE
感谢大佬，请问后续会支持sonoma么？目前博通网卡驱动还是问题不敢升

### ISSUE THREAD

**Issue by CyanogenMod1** [xiecang/Hackintosh-B760M-12490F-6600xt#4]

**Comment by xiecang** [comment]
后续会更新，最近没时间，更好了会推送的

**Comment by cutestAlpaca** [comment]
期待更新

**Comment by songxing10000** [comment]
感谢大佬，期待更新

**Comment by xiecang** [comment]
在 MacBook Pro 上用了一段时间的 Sonoma 了，没有让人眼前一亮的更新，使用起来和 Ventura 区别不大。

目前社区对博通网卡有可驱动的方案了，看起来都不够完美，个人感觉暂时没必要升级，可以等社区有更成熟的解决方案后，再考虑跟进。
