### ISSUE TITLE
一些问题的反馈

### ISSUE THREAD

**Issue by flyflas** [xiecang/Hackintosh-B760M-12490F-6600xt#7]
## 变频问题
CPU: 12400F
主板： 铭瑄B760终结者D4
macOS： Ventura

问题： 使用该EFI，在Ventura中，CPU变频异常。使用intel power gadget软件，监测CPU频率，即使在满载的情况下，CPU最高频率不会超过3.4Ghz。

解决方法： 更换机型为iMac Pro(2017)之后，CPU变频正常，满载可以跑到4.0Ghz。但是部分USB接口不可用（解决方法见下）。

## USB定制问题

问题： 如果机型更换为iMac Pro(2017)之后，部分USB接口失效，免驱卡蓝牙无法使用（USB没有定制造成的）。
解决方法： 建议在Win10下，使用USBToolBox重新定制USB接口。

**Comment by xiecang** [comment]
感谢反馈，确实有CPU变频的问题

[已更新](https://github.com/xiecang/Hackintosh-B760M-12490F-6600xt/commit/bc4adfcda4de5ab2f8560b368ff304a3dac6f295)

不过我没有启用重新定制的 UTBMap.kext 本机上看起来蓝牙也是正常的，比较奇怪，遇到问题的可以自己定制下。
